### PR TITLE
Adding Freehand as a default available tool

### PR DESCRIPTION
**Pull request by MathisGuilhin**
As advised by @dannyrb in https://github.com/OHIF/Viewers/issues/577, here is the PR  that adds freehand as a default availableTool.

### CODE REVIEW

**Comment by dannyrb** [comment]
@MathisGuilhin, I believe the name needs to be `FreehandMouse` to match up with these:

- https://github.com/cornerstonejs/cornerstoneTools/blob/61e947de4f20114c040502278b86b3c5a154c10b/src/tools/annotation/FreehandMouseTool.js#L53
- https://github.com/cornerstonejs/cornerstoneTools/blob/61e947de4f20114c040502278b86b3c5a154c10b/src/index.js#L310

@JamesAPetts has already brought attention to the poor tool naming, as `touch` support has been added, but renaming the tool requires a major version bump

**Comment by MathisGuilhin** [comment]
You're right @dannyrb so I corrected it

**Comment by JamesAPetts** [comment]
P.S. In `cornerstoneTools` `vNext` the freehand tool name will be changed, but this all correct for now.

**Comment by dannyrb** [comment]
@MathisGuilhin I will cut a manual release for this shortly, as I don't believe this repo is using `semantic-release`. I'll put a note here with the new release version when I do.

**Pull request merged**
